### ISSUE TITLE
Error when running dyn.tl.dynamics

### ISSUE THREAD

**Issue by frenkiboy** [aristoteleo/dynamo-release#146]
I get the following error when running dyn.tl.dynamics on the DentateGyrus test data set:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vfranke/bin/Software/miniconda3/envs/scvelo/lib/python3.8/site-packages/dynamo/tools/dynamics.py", line 282, in dynamics
    moments(adata, genes=valid_bools, group=tkey)
  File "/home/vfranke/bin/Software/miniconda3/envs/scvelo/lib/python3.8/site-packages/dynamo/tools/moments.py", line 95, in moments
    kNN, knn_indices, knn_dists, _ = umap_conn_indices_dist_embedding(
  File "/home/vfranke/bin/Software/miniconda3/envs/scvelo/lib/python3.8/site-packages/dynamo/tools/connectivity.py", line 227, in umap_conn_indices_dist_embedding
    embedding_ = simplicial_set_embedding(
TypeError: simplicial_set_embedding() missing 3 required positional arguments: 'densmap', 'densmap_kwds', and 'output_dens'
```

package versions:
```
scvelo 0.2.3
dynamo-release 0.95.2
Python 3.8.8
```

**Comment by Xiaojieqiu** [comment]
Hi @frenkiboy thanks for using our package. dynamo requires umap-learn 0.5.1. you may also upgrade pynndescent to 0.5.2. 

btw, to check the dependencies of all dynamo related packages, try: dyn.get_all_dependencies_version()

**Comment by frenkiboy** [comment]
Dear Xiaojie, 

Thank you so much for the prompt response.

All the dependencies seem to be installed with the proper version:

Conda dump:
```
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alabaster=0.7.12=py_0
  - anndata=0.7.5=py38h578d9bd_0
  - arpack=3.7.0=hdefa2d7_2
  - babel=2.9.0=pyhd3deb0d_0
  - blosc=1.21.0=h9c3ff4c_0
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.12.5=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.6=py38ha5dfef3_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - docutils=0.16=py38h578d9bd_3
  - freetype=2.10.4=h0708190_1
  - get_version=2.1=py_1
  - glpk=4.65=h9202a9a_1003
  - gmp=6.2.1=h58526e2_0
  - h5py=3.1.0=nompi_py38hafa665b_100
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - igraph=0.9.0=h2ed7ec2_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=3.7.3=py38h578d9bd_0
  - importlib_metadata=3.7.3=hd8ed1ab_0
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - legacy-api-wrap=1.2=py_0
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libcurl=7.75.0=hc4aaa36_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=hdc55705_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxml2=2.9.10=h72842e0_3
  - llvmlite=0.36.0=py38h4630a5e_0
  - loompy=3.0.6=py_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - lzo=2.10=h516909a_1000
  - markupsafe=1.1.1=py38h497a2fe_3
  - matplotlib-base=3.3.4=py38h0efea84_0
  - metis=5.1.0=h58526e2_1006
  - mnnpy=0.1.9.5=py38h4a8c8d9_2
  - mock=4.0.3=py38h578d9bd_1
  - natsort=7.1.1=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.5=py_0
  - numba=0.53.0=py38h5e62926_1
  - numexpr=2.7.3=py38h51da96c_0
  - numpy=1.20.1=py38h18fd61f_0
  - numpy_groupies=0.9.13=pyh9f0ad1d_1
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py38h51da96c_0
  - patsy=0.5.1=py_0
  - pillow=8.1.2=py38ha0e1e83_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pynndescent=0.5.2=pyh44b312d_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38h578d9bd_3
  - pytables=3.6.1=py38hc386592_3
  - python=3.8.8=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - scanpy=1.7.1=py_0
  - scikit-learn=0.24.1=py38h658cfdd_0
  - scipy=1.6.1=py38hb2138dd_0
  - scvelo=0.2.3=py_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - setuptools=49.6.0=py38h578d9bd_3
  - setuptools-scm=6.0.1=pyh44b312d_0
  - setuptools_scm=6.0.1=hd8ed1ab_0
  - sinfo=0.3.1=py_0
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.1.0=pyhd8ed1ab_0
  - sphinx=3.5.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.34.0=h74cdb3f_0
  - statsmodels=0.12.2=py38h5c078b8_0
  - stdlib-list=0.7.0=py_2
  - suitesparse=5.7.2=h7a0d4b7_0
  - tbb=2020.2=h4bd325d_4
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.59.0=pyhd8ed1ab_0
  - umap-learn=0.5.1=py38h578d9bd_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - annoy==1.17.0
    - backcall==0.2.0
    - bbknn==1.4.1
    - colorcet==2.0.6
    - cvxopt==1.2.6
    - cython==0.29.22
    - dynamo-release==0.95.2
    - fbpca==1.0
    - geosketch==1.2
    - harmonypy==0.0.5
    - hdbscan==0.8.27
    - intervaltree==2.1.0
    - ipython==7.22.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - louvain==0.7.0
    - numdifftools==0.9.39
    - param==1.10.1
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.18
    - ptyprocess==0.7.0
    - pyct==0.4.8
    - python-igraph==0.9.0
    - scanorama==1.7.1
    - sortedcontainers==2.3.0
    - texttable==1.6.3
    - traitlets==5.0.5
    - trimap==1.0.15
    - wcwidth==0.2.5
```

**Comment by Xiaojieqiu** [comment]
sorry, have you solved this issue or not? Your version of umap seems satisfied. But if not, try upgrade umap-learn / pynndescent again. Those positional arguments: 'densmap', 'densmap_kwds', and 'output_dens' are result from recent API changes in umap-learn. Please let me know how it goes

Also are you installing dynamo via setup install after pulling the newest one from github? we are planning to release 0.93 or 1.0 soon on PyPi

**Comment by frenkiboy** [comment]
Dear Xiaojie, 

I installed everything from pip. Will try to reinstall umap.

Best

**Comment by Xiaojieqiu** [comment]
let me know how it goes, happy to help furture

**Comment by Xiaojieqiu** [comment]
I assume this has addressed. Close it for now

**Comment by amgreaney** [comment]
Hi, I'm having a different issue running dyn.tl.dynamics:

```
In : dyn.tl.dynamics(adata)
|-----> dynamics_del_2nd_moments_key is None. Using default value from DynamoAdataConfig: dynamics_del_2nd_moments_key=False
|-----------> removing existing M layers:[]...
|-----------> making adata smooth...
|-----> calculating first/second moments...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/x/.conda/envs/py392/lib/python3.9/site-packages/dynamo/tools/dynamics.py", line 358, in dynamics
    moments(adata, genes=valid_bools, group=tkey)
  File "/home/x/.conda/envs/py392/lib/python3.9/site-packages/dynamo/tools/moments.py", line 193, in moments
    layer_x_group = np.where([layer in x for x in [only_splicing, only_labeling, splicing_and_labeling]])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

I think my environment and packages are appropriate, I'll document below. There's a chance my input data isn't the correct structure, I converted an integrated seurat object from R using as.loom, but I'm not super familiar with this function. The seurat object contained spliced and unspliced data as assays, do they need to be layers for dynamo? dyn.pp.recipe_monocle(adata) was unable to perform cell cycle staging, but I don't think that's causing this issue. Here's the current data structure, following dyn.read_loom and dyn.pp.recipe_monocle:

```
In : adata
AnnData object with n_obs × n_vars = 42029 × 32883
    obs: ... 'nGenes', 'nCounts', 'pMito', 'pass_basic_filter', 'Size_Factor', 'initial_cell_size', 'counts_Size_Factor', 'initial_counts_cell_size'
    var: 'nCells', 'nCounts', 'pass_basic_filter', 'log_cv', 'log_m', 'score', 'frac', 'use_for_pca'
    uns: 'pp', 'velocyto_SVR', 'PCs', 'explained_variance_ratio_', 'pca_mean', 'pca_fit', 'feature_selection'
    obsm: 'X_pca', 'X'
    layers: 'counts', 'X_counts'

```
Thanks!


```
In : dyn.get_all_dependencies_version()
package umap-learn pynndescent numdifftools python-igraph seaborn statsmodels  \
version      0.5.3       0.5.7       0.9.40        0.10.2  0.12.1      0.13.2   

package   numba dynamo-release scikit-learn cvxopt pandas  scipy   numpy  \
version  0.56.3          1.1.0        1.1.2  1.3.0  1.5.1  1.9.3  1.23.4   

package networkx pre-commit colorcet loompy openpyxl get-version matplotlib  \
version    2.8.7     2.20.0    3.0.1  3.0.7   3.0.10       3.5.4      3.6.0   

package    tqdm setuptools  
version  4.64.1     65.5.0  

```
```
$ pip list
Package                       Version
----------------------------- -----------
algopy                        0.5.7
anndata                       0.7.5
annoy                         1.17.0
asttokens                     2.0.8
attrs                         22.1.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
beautifulsoup4                4.11.1
bleach                        5.0.1
certifi                       2022.9.24
cfgv                          3.3.1
charset-normalizer            2.1.1
click                         8.1.3
colorcet                      3.0.1
contourpy                     1.0.5
cvxopt                        1.3.0
cycler                        0.11.0
decorator                     5.1.1
defusedxml                    0.7.1
distlib                       0.3.6
dunamai                       1.13.2
dynamo-release                1.1.0
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     1.1.1
fastjsonschema                2.16.2
filelock                      3.8.0
fonttools                     4.38.0
get_version                   3.5.4
ghp-import                    2.1.0
gitdb                         4.0.9
GitPython                     3.1.29
h5py                          3.7.0
hdbscan                       0.8.28
identify                      2.5.7
idna                          3.4
igraph                        0.10.2
importlib-metadata            5.0.0
ipython                       8.4.0
jedi                          0.18.1
Jinja2                        3.1.2
joblib                        1.2.0
jsonschema                    4.16.0
jupyter_client                7.4.4
jupyter_core                  4.11.2
jupyterlab-pygments           0.2.2
KDEpy                         1.1.0
kiwisolver                    1.4.4
llvmlite                      0.39.1
loompy                        3.0.7
Markdown                      3.3.7
MarkupSafe                    2.1.1
matplotlib                    3.6.0
matplotlib-inline             0.1.6
mergedeep                     1.3.4
mistune                       2.0.4
mkdocs                        1.4.1
mkdocs-material               8.5.7
mkdocs-material-extensions    1.1
mknotebooks                   0.7.1
more-itertools                9.0.0
natsort                       8.2.0
nbclient                      0.7.0
nbconvert                     7.2.2
nbformat                      5.7.0
nest-asyncio                  1.5.6
networkx                      2.8.7
nodeenv                       1.7.0
numba                         0.56.3
numdifftools                  0.9.40
numpy                         1.23.4
numpy-groupies                0.9.20
nxviz                         0.7.3
openpyxl                      3.0.10
packaging                     21.3
palettable                    3.3.0
pandas                        1.5.1
pandocfilters                 1.5.0
param                         1.12.2
parso                         0.8.3
patsy                         0.5.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.3
platformdirs                  2.5.2
pre-commit                    2.20.0
prompt-toolkit                3.0.31
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyct                          0.4.8
Pygments                      2.13.0
pymdown-extensions            9.7
pynndescent                   0.5.7
pyparsing                     3.0.9
pyrsistent                    0.18.1
python-dateutil               2.8.2
python-igraph                 0.10.2
pytz                          2022.5
PyYAML                        6.0
pyyaml_env_tag                0.1
pyzmq                         24.0.1
requests                      2.28.1
scikit-learn                  1.1.2
scipy                         1.9.3
seaborn                       0.12.1
setuptools                    65.5.0
six                           1.16.0
smmap                         5.0.0
soupsieve                     2.3.2.post1
stack-data                    0.5.1
statsmodels                   0.13.2
texttable                     1.6.4
threadpoolctl                 3.1.0
tinycss2                      1.2.1
toml                          0.10.2
tornado                       6.2
tqdm                          4.64.1
traitlets                     5.5.0
trimap                        1.0.15
umap-learn                    0.5.3
urllib3                       1.26.12
virtualenv                    20.16.6
watchdog                      2.1.9
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.37.1
zipp                          3.10.0
```
