### ISSUE TITLE
value error in basic_stats 

### ISSUE THREAD

**Issue by 117999** [aristoteleo/dynamo-release#219]
Hi Dr.Qiu,

I have recently created a new virtual environment and re-install the newest version of dynamo. When I try to run the `dyn.pl.basic_stats`, error has been reported.  Here follows the detailed code:
```
import scanpy as sc
import scvelo as scv
import dynamo as dyn
import numpy as np
import pandas as pd
```
```
adata=sc.read_10x_mtx('./Gene/raw')
dyn.pl.basic_stats(adata)
```
it reports
```
ValueError                                Traceback (most recent call last)
~/.conda/envs/rpy2/lib/python3.7/site-packages/dynamo/preprocessing/utils.py in basic_stats(adata)
    160     try:
--> 161         adata.obs['pMito'] = (adata[:, mito_genes].X).sum(1).A1 / adata.obs['nCounts'] if issparse(adata.X) else  \
    162             (adata[:, mito_genes].X).sum(1) / adata.obs['nCounts']

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/generic.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
   2028     ):
-> 2029         return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
   2030 

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/arraylike.py in array_ufunc(self, ufunc, method, *inputs, **kwargs)
    252     # for binary ops, use our custom dunder methods
--> 253     result = maybe_dispatch_ufunc_to_dunder_op(self, ufunc, method, *inputs, **kwargs)
    254     if result is not NotImplemented:

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/_libs/ops_dispatch.pyx in pandas._libs.ops_dispatch.maybe_dispatch_ufunc_to_dunder_op()

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/ops/common.py in new_method(self, other)
     68 
---> 69         return method(self, other)
     70 

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/arraylike.py in __rtruediv__(self, other)
    119     def __rtruediv__(self, other):
--> 120         return self._arith_method(other, roperator.rtruediv)
    121 

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/series.py in _arith_method(self, other, op)
   5526 
-> 5527         return self._construct_result(result, name=res_name)
   5528 

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/series.py in _construct_result(self, result, name)
   2943         #  does inference in the case where `result` has object-dtype.
-> 2944         out = self._constructor(result, index=self.index)
   2945         out = out.__finalize__(self)

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    429             elif is_list_like(data):
--> 430                 com.require_length_match(data, index)
    431 

~/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/common.py in require_length_match(data, index)
    527         raise ValueError(
--> 528             "Length of values "
    529             f"({len(data)}) "

ValueError: Length of values (1) does not match length of index (50)

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-4-554c6ad47fde> in <module>
----> 1 dyn.pl.basic_stats(adata)
      2 dyn.pl.basic_stats(adata)

~/.conda/envs/rpy2/lib/python3.7/site-packages/dynamo/plot/preprocess.py in basic_stats(adata, group, figsize, save_show_or_return, save_kwargs)
     42     if len(adata.obs.columns.intersection(['nGenes', 'nCounts', 'pMito'])) != 3:
     43         from ..preprocessing.utils import basic_stats
---> 44         basic_stats(adata)
     45 
     46     df = pd.DataFrame(

~/.conda/envs/rpy2/lib/python3.7/site-packages/dynamo/preprocessing/utils.py in basic_stats(adata)
    162             (adata[:, mito_genes].X).sum(1) / adata.obs['nCounts']
    163     except:
--> 164         raise Exception(f"looks like your var_names may be corrupted (i.e. include nan values)")
    165 
    166 

Exception: looks like your var_names may be corrupted (i.e. include nan values)
```
I have then checked the source code in dynamo/preprocessing/utils.py
```
>>> def basic_stats(adata):
...     adata.obs["nGenes"], adata.obs["nCounts"] = (adata.X > 0).sum(1), (adata.X).sum(1)
...     adata.var["nCells"], adata.var["nCounts"] = (adata.X > 0).sum(0).T, (adata.X).sum(0).T
...     mito_genes = adata.var_names.str.upper().str.startswith("MT-")
...     try:
...         adata.obs["pMito"] = adata.X[:, mito_genes].sum(1) / adata.obs["nCounts"].values.reshape((-1, 1))
...     except:  # noqa E722
...         raise ValueError(
...             "no mitochondria genes detected; looks like your var_names may be corrupted (i.e. "
...             "include nan values). If you don't believe so, please report to us on github or "
...             "via xqiu@wi.mmit.edu"
...         )
... 
>>> basic_stats(adata)
>>> adata.obs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/frame.py", line 1002, in __repr__
    show_dimensions=show_dimensions,
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/core/frame.py", line 1134, in to_string
    line_width=line_width,
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1053, in to_string
    string = string_formatter.to_string()
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/string.py", line 25, in to_string
    text = self._get_string_representation()
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/string.py", line 40, in _get_string_representation
    strcols = self._get_strcols()
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/string.py", line 31, in _get_strcols
    strcols = self.fmt.get_strcols()
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 540, in get_strcols
    strcols = self._get_strcols_without_index()
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 804, in _get_strcols_without_index
    fmt_values = self.format_col(i)
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 825, in format_col
    leading_space=self.index,
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1240, in format_array
    return fmt_obj.get_result()
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1271, in get_result
    fmt_values = self._format_strings()
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1528, in _format_strings
    fmt_values = [formatter(x) for x in self.values]
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1528, in <listcomp>
    fmt_values = [formatter(x) for x in self.values]
  File "/public/home/ycxiang_zju/.conda/envs/rpy2/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1526, in <lambda>
    formatter_str = lambda x: f"{x: d}".format(x=x)
TypeError: unsupported format string passed to matrix.__format__


```
when individually check the` (adata.X > 0).sum(1)`, it appears to be a matrix instead of array, and I convert it with numpy then. 
```
np.array((adata.X > 0).sum(1)).flatten()
df1['nGenes'] = np.array((adata.X > 0).sum(1)).flatten()
adata.X = adata.X.A
dyn.pl.basic_stats(adata)

```
It finally works. 

I am not sure whether the value error is due to the updated version. I have also tried to re-install the dynamo-release 0.95.2, but the same error report. 

Appreciate it a lot if you can help me fix the problem. 

Sincerely,
Yuchen

**Comment by Xiaojieqiu** [comment]
this seems related to pandas, what is your pandas version? try using pandas 1.2.2 or higher

**Comment by wunnies** [comment]
I received the same error with Pandas version 1.3.4, anndata 0.7.5.
The np.array conversion fix provided by 117999 worked for me as well.
