### ISSUE TITLE
Error in dyn.mv.animate_fates

### ISSUE THREAD

**Issue by lh12565** [aristoteleo/dynamo-release#297]
Hi, I am interested in animate fate transition, but I get an error when run the codes:
```python3
progenitor = adata.obs_names[adata.obs.celltype.isin(['Mono'])]
dyn.pd.fate(adata, basis='umap', init_cells=progenitor, interpolation_num=100,  direction='forward',
   inverse_transform=False, average=False, cores=3)
fig, ax = plt.subplots()
ax = dyn.pl.topography(adata, color='celltype', ax=ax, save_show_or_return='return')
dyn.mv.animate_fates(adata, color='celltype', basis='umap', n_steps=100, fig=fig, ax=ax,
                     save_show_or_return='save', logspace=True, max_time=None)
```
```python3
|-----? the number of cell states with fate prediction is more than 50. You may want to lower the max number of cell states to draw via cell_states argument.
MovieWriter stderr:
convert: unexpected end-of-file `-': No such file or directory @ error/rgb.c/ReadRGBImage/243.
convert: no images defined `fate_ani.gif' @ error/convert.c/ConvertImageCommand/3235.
Traceback (most recent call last):
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/matplotlib/animation.py", line 236, in saving
    yield self
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/matplotlib/animation.py", line 1091, in save
    anim._draw_next_frame(d, blit=False)
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/matplotlib/animation.py", line 1126, in _draw_next_frame
    self._draw_frame(framedata)
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/matplotlib/animation.py", line 1720, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/dynamo/movie/fate.py", line 222, in update
    self.ax.lines = []
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/dynamo/movie/fate.py", line 363, in animate_fates
    anim.save(**save_kwargs_)  # save as gif file.
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/matplotlib/animation.py", line 1095, in save
    writer.grab_frame(**savefig_kwargs)
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/matplotlib/animation.py", line 238, in saving
    self.finish()
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/matplotlib/animation.py", line 344, in finish
    self._cleanup()  # Inline _cleanup() once cleanup() is removed.
  File "/NAS/lh/software/miniconda3/envs/dynamonew/lib/python3.8/site-packages/matplotlib/animation.py", line 375, in _cleanup
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['convert', '-size', '640x480', '-depth', '8', '-delay', '10.0', '-loop', '0', 'rgba:-', 'fate_ani.gif']' returned non-zero exit status 1.
```

**Comment by dummyindex** [comment]
Hi @lh12565 ,

Can we have your matplotlib version? You may try installing `matplotlib==3.5.1` and `matplotlib==3.4.3` which we tested the  fate animation utility on.
 
It seems
1) `MovieWriter stderr:` comes from magick 
2) set ax.lines may not be allowed in your matplotlib versions. If this is the issue, I will fix it.

**Comment by lh12565** [comment]
> Hi @lh12565 ,
> 
> Thank you for reporting the issue. Can we have your matplotlib version? You may try installing `matplotlib==3.5.1` and `matplotlib==3.4.3` which we tested the fate animation utility on and I cannot reproduce your issue in my current environment (macOS).
> 
> It seems
> 
> 1. `MovieWriter stderr:` comes from magick
> 2. set ax.lines may not be allowed in your matplotlib versions. If this is the issue, I will fix it.
> 
> Please let us know if downgrading (or upgrading) matplotlib works.

Hi, @dummyindex my matplotlib version is 3.5.1, so I downgraded matplotlib to 3.4.3, but the error is still there:
```
|-----? the number of cell states with fate prediction is more than 50. You may want to lower the max number of cell states to draw via cell_states argument.
MovieWriter stderr:
convert: unexpected end-of-file `-': No such file or directory @ error/rgb.c/ReadRGBImage/243.
convert: no images defined `fate_ani.gif' @ error/convert.c/ConvertImageCommand/3235.
Traceback (most recent call last):
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/matplotlib/a
nimation.py", line 236, in saving
    yield self
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/matplotlib/animation.py", line 1091, in save
    anim._draw_next_frame(d, blit=False)
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/matplotlib/animation.py", line 1126, in _draw_next_frame
    self._draw_frame(framedata)
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/matplotlib/animation.py", line 1720, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/dynamo/movie/fate.py", line 215, in update
    self.ax.lines = []
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/dynamo/movie/fate.py", line 356, in animate_fates
    anim.save(**save_kwargs_)  # save as gif file.
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/matplotlib/animation.py", line 1095, in save
    writer.grab_frame(**savefig_kwargs)
  File "/NAS/lh/software/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/matplotlib/animation.py", line 238, in saving
    self.finish()
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/matplotlib/animation.py", line 344, in finish
    self._cleanup()  # Inline _cleanup() once cleanup() is removed.
  File "/NAS/lh/software/miniconda3/lib/python3.8/site-packages/matplotlib/animation.py", line 375, in _cleanup
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['convert', '-size', '640x480', '-depth', '8', '-delay', '10.0', '-loop', '0', 'rgba:-', 'fate_ani.gif']' returned non-zero exit status 1.
```

**Comment by lh12565** [comment]
> Thanks for letting us know. The issue you mentioned above is related to `imagemagick` on your system. `matplotlib` supports several writer. If you would like to use `animate_fates` with a different writer, you can try add `save_kwargs={"writer": "other_writer"}` to animate_fates args. (other_writer can be `ffmpeg`, `pillow` and others that you can find in matplotlib animation documentation). e.g.
> 
> ```
> dyn.mv.animate_fates(adata, color='celltype', basis='umap', n_steps=100, fig=fig, ax=ax,
>                      save_show_or_return='save', logspace=True, max_time=None, save_kwargs={"writer": "ffmpeg"})
> ```
> 
> Can you also try adapting the following code from our zebrafish notebook for animation https://dynamo-release.readthedocs.io/en/latest/notebooks/zebrafish.html? This may solve your animation needs.
> 
> ```
> fig, ax = plt.subplots()
> ax = dyn.pl.topography(adata, color='Cell_type', ax=ax, save_show_or_return='return')
> 
> instance = dyn.mv.StreamFuncAnim(adata=adata, color='Cell_type', ax=ax)
> import matplotlib
> matplotlib.rcParams['animation.embed_limit'] = 2**128 # Ensure all frames will be embedded.
> 
> from matplotlib import animation
> import numpy as np
> 
> anim = animation.FuncAnimation(instance.fig, instance.update, init_func=instance.init_background,
>                                frames=np.arange(100), interval=100, blit=True)
> from IPython.core.display import display, HTML
> HTML(anim.to_jshtml()) # embedding to jupyter notebook.
> ```

Hi, @dummyindex  I made some changes to the env and it works. Thanks!

**Comment by hyjforesight** [comment]
hello @lh12565 
how did u fix it? Thanks!

**Comment by lh12565** [comment]
> 
Hi, @hyjforesight I rebuild the conda env and downgraded matplotlib to 3.4.3, and it works.
