### ISSUE TITLE
AttributeError: 'AnchoredSizeLocator' object has no attribute 'get_subplotspec'

### ISSUE THREAD

**Issue by hyjforesight** [aristoteleo/dynamo-release#308]
Hello Dynamo,
Thanks for developing this amazing package.
I'm running the `Zebrafish pigmentation` tutorial.
I got no umap plot after running `dyn.pl.umap(adata, color='Cell_type')` and got an error `AttributeError: 'AnchoredSizeLocator' object has no attribute 'get_subplotspec'` when running `dyn.pl.phase_portraits(adata, genes=adata.var_names[adata.var.use_for_dynamics][:4], figsize=(6, 4), color='Cell_type')`.
Could you please help me with this issue?
Thanks!
Best,
YJ

```python
import warnings
warnings.filterwarnings('ignore')

import dynamo as dyn
dyn.configuration.set_pub_style()
dyn.get_all_dependencies_version()
package	pre-commit	colorcet	cvxopt	loompy	matplotlib	networkx	numba	numdifftools	numpy	pandas	pynndescent	python-igraph	scikit-learn	scipy	seaborn	setuptools	statsmodels	tqdm	umap-learn	dynamo-release
version	2.17.0	3.0.0	1.2.7	3.0.6	3.5.1	2.6.3	0.55.0	0.9.40	1.21.5	1.3.5	0.5.5	0.9.9	1.0.2	1.7.3	0.11.2	58.0.4	0.13.1	4.62.3	0.5.2	1.0.0

adata = dyn.sample_data.zebrafish()

dyn.pp.recipe_monocle(adata)

dyn.tl.dynamics(adata, model='stochastic', cores=8)

dyn.tl.reduceDimension(adata, basis='pca')

dyn.pl.umap(adata, color='Cell_type')
# no UMAP generated here

dyn.pl.phase_portraits(adata, genes=adata.var_names[adata.var.use_for_dynamics][:4], figsize=(6, 4), color='Cell_type')
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_9560/1229730937.py in <module>
      1 # check phase diagram
----> 2 dyn.pl.phase_portraits(adata, genes=adata.var_names[adata.var.use_for_dynamics][:4], figsize=(6, 4), color='Cell_type')

~\AppData\Roaming\Python\Python38\site-packages\dynamo\plot\dynamics.py in phase_portraits(adata, genes, x, y, pointsize, vkey, ekey, basis, log1p, color, use_smoothed, highlights, discrete_continous_div_themes, discrete_continous_div_cmap, discrete_continous_div_color_key, discrete_continous_div_color_key_cmap, figsize, ncols, legend, background, show_quiver, quiver_size, quiver_length, no_vel_u, frontier, q_kwargs_dict, show_arrowed_spines, save_show_or_return, save_kwargs, **kwargs)
   1082         with warnings.catch_warnings():
   1083             warnings.simplefilter("ignore")
-> 1084             plt.tight_layout()
   1085 
   1086         plt.show()

c:\programdata\anaconda3\envs\python38\lib\site-packages\matplotlib\pyplot.py in tight_layout(pad, h_pad, w_pad, rect)
   2300 @_copy_docstring_and_deprecators(Figure.tight_layout)
   2301 def tight_layout(*, pad=1.08, h_pad=None, w_pad=None, rect=None):
-> 2302     return gcf().tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
   2303 
   2304 

c:\programdata\anaconda3\envs\python38\lib\site-packages\matplotlib\figure.py in tight_layout(self, pad, h_pad, w_pad, rect)
   3188         from .tight_layout import (
   3189             get_subplotspec_list, get_tight_layout_figure)
-> 3190         subplotspec_list = get_subplotspec_list(self.axes)
   3191         if None in subplotspec_list:
   3192             _api.warn_external("This figure includes Axes that are not "

c:\programdata\anaconda3\envs\python38\lib\site-packages\matplotlib\tight_layout.py in get_subplotspec_list(axes_list, grid_spec)
    232 
    233         if hasattr(axes_or_locator, "get_subplotspec"):
--> 234             subplotspec = axes_or_locator.get_subplotspec()
    235             if subplotspec is not None:
    236                 subplotspec = subplotspec.get_topmost_subplotspec()

c:\programdata\anaconda3\envs\python38\lib\site-packages\matplotlib\colorbar.py in get_subplotspec(self)
    283             if self._orig_locator is None:
    284                 return None
--> 285             ss = self._orig_locator.get_subplotspec()
    286         else:
    287             ss = ss()

AttributeError: 'AnchoredSizeLocator' object has no attribute 'get_subplotspec'
```

**Comment by Xiaojieqiu** [comment]
Hi @hyjforesight thanks for using dynamo. Please check the solution from this https://github.com/aristoteleo/dynamo-release/issues/273

Also you will need to first generate the umap embedding via: `dyn.tl.reduceDimension(adata, basis='umap')`

**Comment by Xiaojieqiu** [comment]
btw, I won't recommend to use windows for scientific programming....

**Comment by hyjforesight** [comment]
Hello @Xiaojieqiu 
Thanks for the response.
I tired `dyn.tl.reduceDimension(adata, basis='umap')`, but still no UMAP was generated. Please see below.
![image](https://user-images.githubusercontent.com/75048821/158283291-a8deb15c-2a1f-4c18-a450-6eb9c3da4017.png)

I followed https://github.com/aristoteleo/dynamo-release/issues/273 and re-install dynamo by
```linux
git clone https://github.com/aristoteleo/dynamo-release.git
cd dynamo-release/
python setup.py install --user
pip install -e .
```
but for the last step `pip install -e .` I encountered below error
```linux
WARNING: Ignoring invalid distribution -nndata (c:\programdata\anaconda3\envs\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -nndata (c:\programdata\anaconda3\envs\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\python38\lib\site-packages)
Obtaining file:///C:/Users/hyjfo/dynamo-release
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\python38\python.exe' 'c:\programdata\anaconda3\envs\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\hyjfo\AppData\Local\Temp\tmpo38nj747'
         cwd: C:\Users\hyjfo\dynamo-release
    Complete output (26 lines):
    Traceback (most recent call last):
      File "c:\programdata\anaconda3\envs\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
        main()
      File "c:\programdata\anaconda3\envs\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\programdata\anaconda3\envs\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\hyjfo\AppData\Local\Temp\pip-build-env-9j0_fiml\overlay\Lib\site-packages\flit_core\buildapi.py", line 49, in prepare_metadata_for_build_wheel
        metadata = make_metadata(module, ini_info)
      File "C:\Users\hyjfo\AppData\Local\Temp\pip-build-env-9j0_fiml\overlay\Lib\site-packages\flit_core\common.py", line 408, in make_metadata
        md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
      File "C:\Users\hyjfo\AppData\Local\Temp\pip-build-env-9j0_fiml\overlay\Lib\site-packages\flit_core\common.py", line 205, in get_info_from_module
        docstring, version = get_docstring_and_version_via_import(target)
      File "C:\Users\hyjfo\AppData\Local\Temp\pip-build-env-9j0_fiml\overlay\Lib\site-packages\flit_core\common.py", line 178, in get_docstring_and_version_via_import
        spec.loader.exec_module(m)
      File "<frozen importlib._bootstrap_external>", line 843, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\hyjfo\dynamo-release\dynamo\__init__.py", line 6, in <module>
        __version__ = get_version(__file__)
      File "C:\Users\hyjfo\dynamo-release\dynamo\get_version.py", line 159, in get_version
        or get_version_from_git(parent)
      File "C:\Users\hyjfo\dynamo-release\dynamo\get_version.py", line 88, in get_version_from_git
        release, dev, hex_, dirty = match_groups(f"{RE_GIT_DESCRIBE}$", p.stdout.rstrip("\r\n"))
      File "C:\Users\hyjfo\dynamo-release\dynamo\get_version.py", line 21, in match_groups
        raise re.error(f"Regex does not match “{target}”. RE Pattern: {regex}", regex)
    re.error: Regex does not match “v1.0.0-594-g84bc4bfe”. RE Pattern: v?(?:([\d.]+)-(\d+)-g)?([0-9a-f]{7})(-dirty)?$
    ----------------------------------------
WARNING: Discarding file:///C:/Users/hyjfo/dynamo-release. Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\python38\python.exe' 'c:\programdata\anaconda3\envs\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\hyjfo\AppData\Local\Temp\tmpo38nj747' Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\python38\python.exe' 'c:\programdata\anaconda3\envs\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\hyjfo\AppData\Local\Temp\tmpo38nj747' Check the logs for full command output.
WARNING: Ignoring invalid distribution -nndata (c:\programdata\anaconda3\envs\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -nndata (c:\programdata\anaconda3\envs\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -nndata (c:\programdata\anaconda3\envs\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\python38\lib\site-packages)
```

**Comment by Xiaojieqiu** [comment]
ok, I think `dyn.tl.reduceDimension(adata, basis='pca')` is actually fine. it will use pca components to by default reduce to umap space. Your adata showed me already included umap embedding. The reason you cannot plot the figure is because a matplotlib version issue. Try install matplotlib version > `3.4.1` or higher. 

Also if you setup install correctly I don't think you need to `rerun pip install -e .` 

Again, windows system is not recommended. In the long run, you should consider switch to linux or macbook as you will for sure face many similar issues when installing other scientific packages.

**Comment by Xiaojieqiu** [comment]
dear @hyjforesight I have looked into the installation issue again and made a few fixes related to `get_version`. If  run ```git clone https://github.com/aristoteleo/dynamo-release.git
cd dynamo-release/
python setup.py install --user
pip install -e .```
it should work fine. 

Please let me know if you still have the plotting issue

**Comment by hyjforesight** [comment]
Hello @Xiaojieqiu 
Thanks for updating the version to v1.1.0. I succeeded in installing this release in Unbuntu.
However, I still got errors when running the Zebrafish pigmentation tutorial.
```python
import warnings
warnings.filterwarnings('ignore')

import dynamo as dyn
dyn.configuration.set_pub_style()
dyn.get_all_dependencies_version()

NoVersionFound                            Traceback (most recent call last)
/tmp/ipykernel_3066/3766699336.py in <module>
      2 warnings.filterwarnings('ignore')
      3 
----> 4 import dynamo as dyn
      5 dyn.configuration.set_pub_style()
      6 dyn.get_all_dependencies_version()

~/.local/lib/python3.9/site-packages/dynamo_release-1.0.0-py3.9.egg/dynamo/__init__.py in <module>
      4 from get_version import get_version
      5 
----> 6 __version__ = get_version(__file__)
      7 del get_version
      8 

~/.local/lib/python3.9/site-packages/get_version-3.5.4-py3.9.egg/get_version/__init__.py in get_version(package, dist_name, vcs)
    278     else:
    279         msg = "\n".join(f"- {e.source.value}:{maybe_indent(e.msg)}" for e in errors)
--> 280         raise NoVersionFound(Source.all, msg)
    281 
    282     assert RE_PEP440_VERSION.match(version)

NoVersionFound: No version found:
- Directory name: name of directory “/home/hyjforesight/.local/lib/python3.9/site-packages/dynamo_release-1.0.0-py3.9.egg” does not contain a valid version.
- VCS: could not find VCS from directory “/home/hyjforesight/.local/lib/python3.9/site-packages/dynamo_release-1.0.0-py3.9.egg”.
- Package metadata: could not find distribution “dynamo”.
```

I did `export PATH=/home/hyjforesight/dynamo-release/:$PATH` in `.bashrc`, but the errors still continue.

Thanks!
Best,
YJ

**Comment by Xiaojieqiu** [comment]
that is very weird. 
make sure you deleted all old versions of dynamo-relase, and then git cloned the latest dynamo and setup installed. Also try updating the get_version package. If all these doesn't help, 

for now you may just comment 
```
      4 from get_version import get_version
      5 
      6 __version__ = get_version(__file__)
      7 del get_version
```
in `dynamo/__init__.py`
and re-try again

**Comment by hyjforesight** [comment]
hello @Xiaojieqiu 
I deleted all old packages, reinstalled again, also updated the `get_version` package and comment in `dynamo/__init__.py`.
The error is still the same. Is it becuase of python3.9.7?
Thanks!
Best,
YJ

**Comment by hyjforesight** [comment]
Change `dyn.configuration.set_pub_style()` to `dyn.configuration.set_figure_params('dynamo', background='white')`, problem solved.
