### ISSUE TITLE
The link https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.pd.fate.html#dynamo.pd.fate seems has lapsed

### ISSUE THREAD

**Issue by stupidstupidstupidstupid** [aristoteleo/dynamo-release#329]
Hello dynamo
The link of function "dynamo.pd.fate" seems has lapsed
 It shows          "SORRY    This page does  not exist yet. "                 now

**Comment by stupidstupidstupidstupid** [comment]
Hello dynamo
I met an error when I tried to run the function dyn.pd.fate

dyn.pd.fate(adata, init_cells=list, init_states=None, basis=None, layer='X', dims=None, genes=None, t_end=None, direction='both', interpolation_num=250, average=False, sampling='arc_length', VecFld_true=None, inverse_transform=False, Qkey='PCs', scale=1, cores=1, **kwargs)
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-978847170e37>", line 1, in <cell line: 1>
    dyn.pd.fate(adata, init_cells=list, init_states=None, basis=None, layer='X', dims=None, genes=None, t_end=None, direction='both', interpolation_num=250, average=False, sampling='arc_length', VecFld_true=None, inverse_transform=False, Qkey='PCs', scale=1, cores=1, **kwargs)
NameError: name 'kwargs' is not defined

What should I do to fix it?
