### ISSUE TITLE
Unable to download sample data

### ISSUE THREAD

**Issue by FionaMoon** [aristoteleo/dynamo-release#412]
Hi, dynamo group
I'm learning dynamo following the tutorial, but sometimes it's hard to download sample data especially when I stay at home.
```
>>> adata = dyn.sample_data.zebrafish()
|-----> Downloading data to ./data/zebrafish.h5ad
Traceback (most recent call last):
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/site-packages/dynamo/sample_data.py", line 120, in zebrafish
    adata = get_adata(url, filename)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/site-packages/dynamo/sample_data.py", line 41, in get_adata
    file_path = download_data(url, filename)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/site-packages/dynamo/sample_data.py", line 22, in download_data
    urlretrieve(url, file_path, reporthook=LoggerManager.get_main_logger().request_report_hook)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/xtdisk/KB/miniconda/envs/velocity/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
```

Can you provide other ways for users to get sample data?

Thank you inadvance !

Fiona

**Comment by Xiaojieqiu** [comment]
thanks for using dynamo, @FionaMoon. Our datasets are hosted on dropbox. Please make sure you have access to dropbox. You may need to use a VPN.

**Comment by Xiaojieqiu** [comment]
We may eventually host the data to some servers in our lab in the near future
