### ISSUE TITLE
defects in `get_data` failed the sample data and blocked the unit test cases 

### ISSUE THREAD

**Issue by chansigit** [aristoteleo/dynamo-release#687]
The `get_data` function is the foundation of many sample data functions. Its failure made a lot of test cases failed too.  

When running the `get_data` function, I got the following errors. 

Note that I'm running the code on our US-based lenovo server so it's not the VPN problem.

```
(dynode) dingjia5@tag-308:~/sijie-work/projects/dynamo-release$ python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dynamo
from dynamo.sample_data import get_adata

2024-07-04 04:24:30.589005: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-04 04:24:31.551803: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/dingjia5/micromamba/envs/dynode/lib/python3.9/site-packages/numba/np/ufunc/dufunc.py:343: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
  warnings.warn(msg, errors.NumbaWarning)
/home/dingjia5/micromamba/envs/dynode/lib/python3.9/site-packages/numba/np/ufunc/dufunc.py:343: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
  warnings.warn(msg, errors.NumbaWarning)
/home/dingjia5/micromamba/envs/dynode/lib/python3.9/site-packages/numba/np/ufunc/dufunc.py:343: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
  warnings.warn(msg, errors.NumbaWarning)

In : from dynamo.sample_data import get_adata
In : get_adata(url = 'https://www.dropbox.com/scl/fi/3zt89ee0j5twxk4ttzmij/zebrafish.h5ad?rlkey=phwg0b7aqiizd9kf69l2kciak&dl=1', 
...:           filename = 'zebrafish.h5ad')
```

```
|-----> Downloading data to ./data/zebrafish.h5ad
Traceback (most recent call last):
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dingjia5/sijie-work/projects/dynamo-release/dynamo/sample_data.py", line 43, in get_adata
    file_path = download_data(url, filename)
  File "/home/dingjia5/sijie-work/projects/dynamo-release/dynamo/sample_data.py", line 24, in download_data
    urlretrieve(url, file_path, reporthook=LoggerManager.get_main_logger().request_report_hook)
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/dingjia5/micromamba/envs/dynode/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dingjia5/sijie-work/projects/dynamo-release/dynamo/sample_data.py", line 54, in get_adata
    main_info("Corrupted file. Deleting " + file_path + " then redownloading...")
UnboundLocalError: local variable 'file_path' referenced before assignment
```

The problem is two-fold:
1) we got `Connection reset by peer` when trying to download the data. I've double checked that the link (https://www.dropbox.com/scl/fi/3zt89ee0j5twxk4ttzmij/zebrafish.h5ad?rlkey=phwg0b7aqiizd9kf69l2kciak&dl=1) is accessible via my chrome browser. This could be some dropbox anti-spider regulations that restricts accessing data without browser.
2) the design of the function is problematic. when https://github.com/chansigit/dynamo-release/blob/2e7eb21b22c20e385853fbfb1a32aba745627e3f/dynamo/sample_data.py#L44 failed, calling the uninitialized `file_path`would be problematic (https://github.com/chansigit/dynamo-release/blob/2e7eb21b22c20e385853fbfb1a32aba745627e3f/dynamo/sample_data.py#L55)

**Comment by Sichao25** [comment]
For problem 2, how about removing the `OSError` part that handles duplicate files? I feel like it should be fine to raise an error message when the download fails for any reason. Additionally, deleting users' existing files does not sound like a good behavior to me. At least we should seek user consent with an extra parameter before replacing any existing files.
